### ISSUE TITLE
Fastfetch instead of neofetch

### ISSUE THREAD

**Issue by IcyAlmond** [Adeon18/.dotfiles#1]
May I suggest you use, [fastfetch](https://github.com/LinusDierheimer/fastfetch) instead of neofetch. 

https://github.com/LinusDierheimer/fastfetch

I see that you make neofetch run every time you start your terminal, but neofetch is very slow, try fastfetch.

**Comment by Adeon18** [comment]
Wow, thank you! Will try fastfetch as soon as I can :)

**Comment by Adeon18** [comment]
Decided to use neofetch, due to it being more easily customized. Maybe will change it in the future.
